// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.fanbar.cw.domain;

import org.fanbar.cw.domain.Auth;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Auth_Roo_Configurable {
    
    declare @type: Auth: @Configurable;
    
}
