// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.fanbar.cw.domain;

import org.fanbar.cw.domain.Regalia;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Regalia_Roo_Configurable {
    
    declare @type: Regalia: @Configurable;
    
}
